<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="2" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-02-03T11:58:16 IST" name="Demo" finished-at="2024-02-03T11:58:53 IST" duration-ms="37259">
    <groups>
    </groups>
    <test started-at="2024-02-03T11:58:16 IST" name="Test" finished-at="2024-02-03T11:58:53 IST" duration-ms="37259">
      <class name="com.awt.test.Login.VerifyLogInFunctionalityTest">
        <test-method is-config="true" signature="launchBrowser(java.lang.String)[pri:0, instance:com.awt.test.Login.VerifyLogInFunctionalityTest@6572421]" started-at="2024-02-03T11:58:16 IST" name="launchBrowser" finished-at="2024-02-03T11:58:31 IST" duration-ms="15053" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method signature="verifyLogInFunctionalityTest()[pri:0, instance:com.awt.test.Login.VerifyLogInFunctionalityTest@6572421]" started-at="2024-02-03T11:58:31 IST" name="verifyLogInFunctionalityTest" finished-at="2024-02-03T11:58:49 IST" duration-ms="17884" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [false] but found [Email/Username or Password is not Valid]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [Email/Username or Password is not Valid]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.awt.utills.reusablecomponents.SoftAssertTest.assertAll(SoftAssertTest.java:154)
at com.awt.test.Login.VerifyLogInFunctionalityTest.verifyLogInFunctionalityTest(VerifyLogInFunctionalityTest.java:44)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogInFunctionalityTest -->
        <test-method is-config="true" signature="tearUp()[pri:0, instance:com.awt.test.Login.VerifyLogInFunctionalityTest@6572421]" started-at="2024-02-03T11:58:52 IST" name="tearUp" finished-at="2024-02-03T11:58:53 IST" duration-ms="363" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearUp -->
      </class> <!-- com.awt.test.Login.VerifyLogInFunctionalityTest -->
    </test> <!-- Test -->
  </suite> <!-- Demo -->
</testng-results>
